name: Selenium Test Cases Execution - CI
	
	on:
	  workflow_dispatch:
	    # Inputs the workflow accepts.
	    inputs:
	      name:
	        type: choice
	        description: 'Deploy to:'
	        options:
	          - None
	          - DEV
	          - INT
	          - TEST
	        required: true
	
	jobs:
	  build:
	    runs-on: [self-hosted]
	
	    steps:
	      - name: Checkout code
	        uses: actions/checkout@v3
	
	      - name: Set up JDK 11
	        uses: actions/setup-java@v3
	        with:
	          java-version: '11'
	          distribution: 'temurin'
	          cache: maven
	
	      - name: Set up Chrome
	        uses: browser-actions/setup-chrome@latest
	      - if: runner.os == 'Linux'
	        run: chrome --version
	   #   - name: Check Chrome version
	   #     run: google-chrome --version
	
	      - name: Build with Maven
	        run: mvn test clean
	        
	  #    - name: Test Reporter
	  #      uses: dorny/test-reporter@v1.4.3
	#         with:
	#             name: Run Tests
	#             path: "**/surefire-reports/TEST-*.xml"
	#             reporter: java-junit    
